myproject/urls.py
from django.urls import path, include, re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from socialapp.views import HomePageView, UserPageView, SendMesageView, CreateUserView, NotificationView, LikeView, \
    update_profile, AddUserPhoto, DelPhoto, ReadMesageView
from rest_framework import routers
from socialapp.views import UserView


router = routers.DefaultRouter()
router.register(r'users', UserView)

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', HomePageView.as_view(), name="homepage"),
                  path('noti/', NotificationView.as_view(), name="notihomepage"),
                  path('<int:pk>', LikeView.as_view(), name="likehomepage"),
                  path('login/', auth_views.LoginView.as_view(), name="login"),
                  path('logout/', auth_views.LogoutView.as_view(), name="logout"),
                  path('profile/<int:pk>', UserPageView.as_view(), name="userpage"),
                  path('mesage/', SendMesageView.as_view(), name="mesage"),
                  path('mesage/read/<int:pk>', ReadMesageView.as_view(), name="readmesage"),
                  path('avatar/', include('avatar.urls')),
                  path('createuser/', CreateUserView.as_view(), name="createuser"),
                  path('updateuser/', update_profile, name="updateuser"),
                  path('adduserphoto/', AddUserPhoto.as_view(), name="adduserphoto"),
                  path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
                      template_name='registration/password_change_d.html'),
                       name='password_change_done'),

                  path('password_change/',
                       auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
                       name='password_change'),

                  path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
                      template_name='registration/password_reset_d.html'),
                       name='password_reset_done'),

                  path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
                       name='password_reset_confirm'),
                  path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='password_reset'),

                  path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
                      template_name='registration/password_reset_c.html'),
                       name='password_reset_complete'),
                  re_path(r'^(?P<pk>\d+)/delphoto/', DelPhoto.as_view(), name="del-photo"),
                  path('', include(router.urls)),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver

class Gossip(models.Model):
    content = models.TextField(max_length=200)
    creation_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    photo = models.ImageField(upload_to="gossip_picture", null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=25)


class Mesage(models.Model):
    title = models.CharField(max_length=35)
    content = models.TextField(max_length=600)
    sender = models.ForeignKey(get_user_model(), related_name="sender", on_delete=models.SET_NULL, null=True,)
    receiver = models.ForeignKey(get_user_model(), related_name="receiver", on_delete=models.SET_NULL, null=True,)
    timestamp = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)
    creation_date = models.DateTimeField(auto_now_add=True)

class Notification(models.Model):
    content =  models.TextField(max_length=200)
    sender = models.ForeignKey(get_user_model(), related_name="sender_not", on_delete=models.SET_NULL, null=True)
    receiver = models.ForeignKey(get_user_model(), related_name="receiver_not", on_delete=models.SET_NULL, null=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    gossip = models.ForeignKey(Gossip, on_delete=models.SET_NULL, null=True)
    created = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    content = models.TextField(max_length=200)
    creation_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    gossip = models.ForeignKey(Gossip, on_delete=models.CASCADE, null=True)

    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True, default="Warsaw")
    birth_date = models.DateField(null=True, blank=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()


class UserImage(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=35, null=True, blank=True)
    photo = models.ImageField(upload_to="user_picture", null=True, blank=True)

socialapp/views.py
from django.shortcuts import render
from django.views import View
from .models import Gossip, Mesage, Notification, Like, Comment, Profile, UserImage
from .forms import GossipForm, MessageForm, CreateUserForm, Notiform, CommentForm, UserForm, ProfileForm, AddUserPhotoForm
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.contrib.auth import get_user_model
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.db import transaction
from .serializers import UserSerializer
from rest_framework import viewsets
import requests
from django.contrib.auth import authenticate, login
from django.views.generic import CreateView, DeleteView


class UserView(viewsets.ModelViewSet, LoginRequiredMixin):
    queryset = User.objects.all()
    serializer_class = UserSerializer


def weather_city(self, city):
    url = 'http://api.openweathermap.org/data/2.5/weather?q={}&units=metric&appid=0a46cddf36d359427e8aa984fb4f0eca'
    city_weather = requests.get(url.format(city)).json()
    weather = {
        'city': city,
        'temperature': city_weather['main']['temp'],
        'description': city_weather['weather'][0]['description'],
        'icon': city_weather['weather'][0]['icon']
    }
    return weather


class HomePageView(View, LoginRequiredMixin):
    def get(self, request):
        if request.user.is_authenticated:
            gossips = Gossip.objects.all().order_by("-id")
            noti = Notification.objects.filter(receiver=request.user, read=False)
            noti_form = Notiform()
            form = GossipForm()
            weather = weather_city(self, request.user.profile.location)
            ctx = {
                "gossips": gossips,
                "form": form,
                "noti": noti,
                "noti_form": noti_form,
                'weather': weather
            }
        else:
            return redirect("/login/")
        return render(request, "homapageone.html", ctx)


    def post(self, request):
        gossips = Gossip.objects.all().order_by("-id")
        weather = weather_city(self, request.user.profile.location)
        form = GossipForm(request.POST or None, request.FILES or None)
        noti = Notification.objects.filter(receiver=request.user, read=False)
        noti_form = Notiform()
        if form.is_valid():
            if request.user.is_authenticated:
                Gossip.objects.create(**form.cleaned_data, user=request.user)
                form = GossipForm()
            else:
                Gossip.objects.create(**form.cleaned_data)

        ctx = {
            "gossips": gossips,
            "form": form,
            "noti": noti,
            "noti_form": noti_form,
            'weather': weather
        }
        return render(request, "homapageone.html", ctx)


class UserPageView(View, LoginRequiredMixin):
    def get(self, request, pk):
        user = User.objects.get(id=pk)
        form = GossipForm()
        weather = weather_city(self, request.user.profile.location)
        if request.user.is_authenticated:
            gossips = Gossip.objects.filter(user=request.user).order_by("-id")
            ctx = {
                "user": user,
                "gossips": gossips,
                "form": form,
                'weather': weather
            }
        else:
            return redirect("/login/")
        return render(request, "userprofile.html", ctx)

    def post(self, request, pk):
        user = User.objects.get(id=pk)
        gossips = Gossip.objects.filter(user=request.user).order_by("-id")
        form = GossipForm(request.POST or None, request.FILES or None)
        weather = weather_city(self, request.user.profile.location)
        if form.is_valid():
            Gossip.objects.create(**form.cleaned_data, user=request.user)
            ctx = {
                "user": user,
                "gossips": gossips,
                "form": form,
                'weather': weather
            }
        return render(request, "userprofile.html", ctx)


class SendMesageView(View, LoginRequiredMixin):
    def get(self, request):
        if request.user.is_authenticated:
            noti = Notification.objects.filter(receiver=request.user, read=False)
            user_mesage = Mesage.objects.filter(receiver=request.user).order_by("-id")
            form = MessageForm()
            ctx = {
                "form": form,
                "user_mesage": user_mesage,
                "noti": noti,
            }
        else:
            return redirect("/login/")
        return render(request, "sendmesage.html", ctx)

    def post(self, request):
        form = MessageForm(request.POST or None, request.FILES or None)
        user_mesage = Mesage.objects.filter(receiver=request.user).order_by("-id")
        noti = Notification.objects.filter(receiver=request.user, read=False)
        if form.is_valid():
            Mesage.objects.create(**form.cleaned_data, sender=request.user)
            receiver_not = form.cleaned_data["receiver"]
            Notification.objects.create(sender=request.user, receiver=receiver_not,
                                        content=f'{request.user.first_name} {request.user.last_name} send you Mesage!!')
            form = MessageForm()
        ctx = {
            "form": form,
            "user_mesage": user_mesage,
            "noti": noti,
        }
        return render(request, "sendmesage.html", ctx)

class ReadMesageView(View, LoginRequiredMixin):
    def post(self, request, pk):
        if request.user.is_authenticated:
            form = MessageForm(request.POST or None, request.FILES or None)
            user_mesage = Mesage.objects.filter(receiver=request.user).order_by("-id")
            mesage = Mesage.objects.get(id=pk)
            if form.is_valid():
                Mesage.objects.create(**form.cleaned_data, sender=request.user)
                receiver_not = form.cleaned_data["receiver"]
                Notification.objects.create(sender=request.user, receiver=receiver_not,
                                            content=f'{request.user.first_name} {request.user.last_name} send you Mesage!!')
                form = MessageForm()
            ctx = {
                "form": form,
                "user_mesage": user_mesage,
            }
            if 'read' in request.POST:
                mesage.read=True
                mesage.save()
        else:
            return redirect("/login/")
        return render(request, "sendmesage.html", ctx)
class CreateUserView(View):
    def get(self, request):
        logout(request)
        form = CreateUserForm()
        ctx = {
            "form": form,
        }
        return render(request, "createuser.html", ctx)

    def post(self, request):
        form = CreateUserForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if form.is_valid():
            form.cleaned_data.pop("repeated_password")
            user = get_user_model().objects.create_user(**form.cleaned_data)
            new_user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password'],
                                    )
            login(request, new_user)
            return redirect("/")
        return render(request, "createuser.html", {"form": form})


class NotificationView(View, LoginRequiredMixin):
    def post(self, request):
        weather = weather_city(self, request.user.profile.location)
        gossips = Gossip.objects.all().order_by("-id")
        noti = Notification.objects.filter(receiver=request.user, read=False)
        form = GossipForm(request.POST or None, request.FILES or None)
        if request.POST is not None:
        # if request.POST.get('read') is not None:
            noti.update(read=True)
        return render(request, "homapageone.html",
                      {"form": form, "gossips": gossips, "noti": noti, 'weather': weather})




class LikeView(View, LoginRequiredMixin):
    def post(self, request, pk):
        weather = weather_city(self, request.user.profile.location)
        gossips = Gossip.objects.all().order_by("-id")
        noti = Notification.objects.filter(receiver=request.user, read=False)
        gos_com_id = pk
        gos_user = Gossip.objects.get(pk=pk).user
        noti_form = Notiform()
        form = GossipForm()
        if 'add' in request.POST:
            Like.objects.get_or_create(user=request.user, gossip_id=pk)
            Notification.objects.create(sender=request.user, receiver=gos_user,
                                        content=f'{request.user.first_name} {request.user.last_name} liked you Post!!')

            comment_form = None
        if 'sub' in request.POST:
            Like.objects.filter(user=request.user).delete()
            Notification.objects.create(sender=request.user, receiver=gos_user,
                                        content=f'{request.user.first_name} {request.user.last_name} unliked you Post!!')
            comment_form = None
        if 'com' in request.POST:
            comment_form = CommentForm()
        if 'add_com' in request.POST:
            content = request.POST["content"]
            Comment.objects.get_or_create(user=request.user, gossip_id=pk, content=content)
            Notification.objects.create(sender=request.user, receiver=gos_user,
                                        content=f'{request.user.first_name} {request.user.last_name} live you comment!!')

            comment_form = None
        ctx = {
            "gossips": gossips,
            "noti": noti,
            "noti_form": noti_form,
            "comment_form": comment_form,
            "gos_com_id": gos_com_id,
            "weather": weather,
            "form": form,

        }
        return render(request, "homapageone.html", ctx)



@login_required
@transaction.atomic

socialapp/templates/adduserphoto.html
{% extends "base.html" %}
{% load bootstrap %}


{% block title%}Login{% endblock %}

{% block content%}
{%for i in photo %}
<img src="/media/{{ i.photo }}" class="center" style="width: 220px"
                                 class="w3-margin-bottom">
<a href="{% url 'del-photo' i.id %}">
            <i class="fas fa-trash-alt"></i></a>
{% endfor %}
<form action="{% url 'adduserphoto' %}" method="POST" enctype="multipart/form-data">
    <table>
        {% csrf_token %}
        {{ add_image|bootstrap }}
    </table>
    <input type="submit" value="Add photo!">
</form>
{% endblock %}

socialapp/templates/homapageone.html
{% extends "base.html" %}
{% load bootstrap %}
{% block title%}Home Page{% endblock %}
{% block content %}
{% load avatar_tags %}

<!-- Navbar on small screens -->
<div id="navDemo" class="w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium w3-large">
    <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 1</a>
    <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 2</a>
    <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 3</a>
    <a href="#" class="w3-bar-item w3-button w3-padding-large">My Profile</a>
</div>

<div class="w3-container w3-content" style="max-width:1400px;margin-top:80px">
    <!-- The Grid -->
    <div class="w3-row">
        <!-- Left Column -->
        <div class="w3-col m3">
            <!-- Profile -->
            <div class="w3-card w3-round w3-white">
                <div class="w3-container">

                    <a href="{% url 'userpage' user.pk %}"><h4 class="w3-center">{{ user.get_full_name }}</h4></a>
                    <p class="w3-center">{% avatar user 223 %}</p>
                    <hr>
                    <p><i class="fa fa-pencil fa-fw w3-margin-right w3-text-theme"></i> {{ user.profile.bio }}</p>
                    <p><i class="fa fa-home fa-fw w3-margin-right w3-text-theme"></i> {{ user.profile.location }}</p>
                    <p><i class="fa fa-birthday-cake fa-fw w3-margin-right w3-text-theme"></i>
                        {{ user.profile.birth_date }}</p>
                </div>
            </div>
            <br>

            <!-- Accordion -->
            <div class="w3-card w3-round">
                <div class="w3-white">
                         <button onclick="myFunction('Demo3')" class="w3-button w3-block w3-theme-l1 w3-left-align"><i
                            class="fa fa-users fa-fw w3-margin-right"></i> My Photos
                    </button>
                    <div id="Demo3" class="w3-hide w3-container">
                        <div class="w3-row-padding">
                            <br>
                            {% for pht in user.userimage_set.all %}
                            <div class="w3-half">
                                <img src="/media/{{ pht.photo }}" style="width:100%" class="w3-margin-bottom">
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <br>


            <!-- End Left Column -->
        </div>

        <!-- Middle Column -->
        <div class="w3-col m7">

            <div class="w3-row-padding">
                <div class="w3-col m12">
                    <div class="w3-card w3-round w3-white">
                        <div class="w3-container w3-padding">
                            <form action="{% url 'homepage' %}" method="POST" enctype='multipart/form-data'>
                                {% csrf_token %}
                                <h5 class="mt-0">I heard that {{ form.title }} - write your title</h5>
                                <p contenteditable="true" id="id_content_gossip" class="w3-border w3-padding">
                                    {{ form.content }} What did you
                                    heard? {{ form.photo }}</p>
                                <button type="submit" class="w3-button w3-theme"><i class="fa fa-pencil"></i> Spread
                                    Gossip!
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            {% for gossip in gossips %}
            <form action="{% url 'likehomepage' gossip.id %}#form-{{ gossip.id }}" method="POST" enctype='multipart/form-data' id="form-{{ gossip.id }}">
                {% csrf_token %}
                <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
                    <div alt="Avatar" class="w3-left w3-circle w3-margin-right">{% avatar gossip.user 62 %}</div>
                    <span class="w3-right w3-opacity">{{ gossip.creation_date }}</span>
                    <h4>{{ gossip.user }} heard that {{ gossip.title }}</h4><br>
                    <hr class="w3-clear">
                    <p>{{ gossip.content }}</p>
                    <div class="w3-row-padding" style="margin:0 -16px">
                        {% if gossip.photo %}
                        <div class="w3-half">
                            <img src="/media/{{ gossip.photo }}" class="center" style="width: 220px"
                                 class="w3-margin-bottom">
                        </div>
                        {% else %}


                        {% endif %}
                    </div>
                    <p class="btn btn-success w3-margin-bottom"> {{ gossip.like_set.count }} person like this</p>
                    <button name="add" type="submit" class="w3-button w3-theme-d1 w3-margin-bottom"><i
                            class="fa fa-thumbs-up"></i> Like
                    </button>
                    <button name="sub" type="submit" class="w3-button w3-theme-d1 w3-margin-bottom"><i
                            class="far fa-thumbs-down"></i> UnLike
                    </button>
                    <button name="com" type="submit" class="w3-button w3-theme-d2 w3-margin-bottom"><i
                            class="fa fa-comment"></i> Comment
                    </button>
                    {% for com in gossip.comment_set.all %}
                    <hr>
                    <ul>{{ com.user }} {% avatar com.user 30 %}</ul>
                    <ul>{{ com.content }}</ul>
                    <hr>
                    {% endfor %}
                    {% if comment_form and gossip.id == gos_com_id %}
                    <p id="scrollhere" > </p>
                    <form action="{% url 'likehomepage' gossip.id %}" method="POST" enctype='multipart/form-data'>
                        {{ comment_form }}
                        {% csrf_token %}
                        <button name="add_com" type="submit" class="w3-button w3-theme-d2 w3-margin-bottom"><i
                                class="fa fa-comment"></i> ADD Comment
                        </button>
                    </form>
                    {% endif %}
                </div>
            </form>
            {% endfor %}
            <!-- End Middle Column -->
        </div>

        <!-- Right Column -->

        <div class="w3-col m2">

            <div class="w3-card w3-round w3-white w3-center">
                <div class="w3-container">
                    <p>Your weather in {{ weather.city }}</p>
                    <img src="http://openweathermap.org/img/wn/{{ weather.icon }}@2x.png">
                    <p><strong><i class="fas fa-temperature-low"></i>{{ weather.temperature }} Celsius</strong></p>
                    <p>
                        <p class="w3-button w3-block w3-theme-l4">{{ weather.description }}</p>
                    </p>
                </div>
            </div>
            <br>


        </div>

        <!-- End Grid -->
    </div>

    <!-- End Page Container -->
</div>
<br>

<!-- Footer -->
<footer class="w3-container w3-theme-d3 w3-padding-16">
    <h5>Footer</h5>
</footer>

<footer class="w3-container w3-theme-d5">
    <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
</footer>

<script>
    // Accordion
    function myFunction(id) {
        var x = document.getElementById(id);
        if (x.className.indexOf("w3-show") == -1) {
            x.className += " w3-show";
            x.previousElementSibling.className += " w3-theme-d1";
        } else {
            x.className = x.className.replace("w3-show", "");
            x.previousElementSibling.className =
                x.previousElementSibling.className.replace(" w3-theme-d1", "");
        }
    }

    // Used to toggle the menu on smaller screens when clicking on the menu button
    function openNav() {
        var x = document.getElementById("navDemo");
        if (x.className.indexOf("w3-show") == -1) {
            x.className += " w3-show";
        } else {
            x.className = x.className.replace(" w3-show", "");
        }
    }
</script>

</body>
{% endblock %}
</html>

socialapp/templates/userprofile.html
{% extends "base.html" %}
{% load bootstrap %}
{% block title%}Home Page{% endblock %}
{% block content %}
{% load avatar_tags %}
<!-- Navbar on small screens -->
<div id="navDemo" class="w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium w3-large">
    <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 1</a>
    <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 2</a>
    <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 3</a>
    <a href="#" class="w3-bar-item w3-button w3-padding-large">My Profile</a>
</div>

<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:1400px;margin-top:80px">
    <!-- The Grid -->
    <div class="w3-row">
        <!-- Left Column -->
        <div class="w3-col m3">
            <!-- Profile -->
            <div class="w3-card w3-round w3-white">
                <div class="w3-container">
                    <h4 class="w3-center">{{ user.get_full_name }}</h4>
                    <p class="w3-center">
                    <p class="w3-center">{% avatar user 211 %}</p></p>
                    <hr>
                    <h2>{{ user.first_name }}</h2>
                    <p>{{ user.profile.bio }}</p>
                    <ul>

                        <li>Username: {{ user.username }}</li>
                        <li>Location: {{ user.profile.location }}</li>
                        <li>Birth Date: {{ user.profile.birth_date }}</li>
                    </ul>
                    <p><a href="{% url 'adduserphoto' %}"><i class="fa fa-pencil fa-fw w3-margin-right w3-text-theme"></i> Add photo</a></p>
                    <p><i class="fa fa-home fa-fw w3-margin-right w3-text-theme"></i> London, UK</p>
                    <p><i class="fa fa-birthday-cake fa-fw w3-margin-right w3-text-theme"></i> April 1, 1988</p>
                </div>
            </div>
            <br>
            <!-- Accordion -->
            <div class="w3-card w3-round">
                <div class="w3-white">

                    <button onclick="myFunction('Demo3')" class="w3-button w3-block w3-theme-l1 w3-left-align"><i
                            class="fa fa-users fa-fw w3-margin-right"></i> My Photos
                    </button>
                    <div id="Demo3" class="w3-hide w3-container">
                        <div class="w3-row-padding">
                            <br>
                            {% for pht in user.userimage_set.all %}
                            <div class="w3-half">
                                <img src="/media/{{ pht.photo }}" style="width:100%" class="w3-margin-bottom">
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <br>


            <!-- End Left Column -->
        </div>

        <!-- Middle Column -->
        <div class="w3-col m7">

            <div class="w3-row-padding">
                <div class="w3-col m12">
                    <div class="w3-card w3-round w3-white">
                        <div class="w3-container w3-padding">
                            <form action="{% url 'homepage' %}" method="POST" enctype='multipart/form-data'>
                                {% csrf_token %}
                                <h5 class="mt-0">I heard that {{ form.title }} - write your title</h5>
                                <p contenteditable="true" class="w3-border w3-padding">{{ form.content }} What did you
                                    heard? {{ form.photo }}</p>
                                <button type="submit" class="w3-button w3-theme"><i class="fa fa-pencil"></i> Spread
                                    Gossip!
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            {% for gossip in gossips %}
            <form action="{% url 'homepage' %}" method="POST" enctype='multipart/form-data'>
                <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
                    <div alt="Avatar" class="w3-left w3-circle w3-margin-right">{% avatar gossip.user 60 %}</div>
                    <span class="w3-right w3-opacity">{{ gossip.creation_date }}</span>
                    <h4>{{ gossip.user }} heard that {{ gossip.title }}</h4><br>
                    <hr class="w3-clear">
                    <p>{{ gossip.content }}</p>
                        {% if gossip.photo %}
                        <div class="w3-half">
                            <img src="/media/{{ gossip.photo }}" class="center" style="width: 220px"
                                 class="w3-margin-bottom">
                        </div>
                        {% else %}
                        {% endif %}

            </form>
        </div>
        {% endfor %}
        <!-- End Middle Column -->
    </div>

    <!-- Right Column -->
    <div class="w3-col m2">
            <div class="w3-card w3-round w3-white w3-center">
                <div class="w3-container">
                    <p>Your weather in {{ weather.city }}</p>
                    <img src="http://openweathermap.org/img/wn/{{ weather.icon }}@2x.png">
                    <p><strong><i class="fas fa-temperature-low"></i>{{ weather.temperature }} Celsius</strong></p>
                    <p>
                        <p class="w3-button w3-block w3-theme-l4">{{ weather.description }}</p>
                    </p>
                </div>
            </div>
            <br>

        <!-- End Right Column -->
    </div>

    <!-- End Grid -->
</div>

<!-- End Page Container -->
</div>
<br>

<!-- Footer -->
<footer class="w3-container w3-theme-d3 w3-padding-16">
    <h5>Footer</h5>
</footer>

<footer class="w3-container w3-theme-d5">
    <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
</footer>

<script>
    // Accordion
    function myFunction(id) {
        var x = document.getElementById(id);
        if (x.className.indexOf("w3-show") == -1) {
            x.className += " w3-show";
            x.previousElementSibling.className += " w3-theme-d1";
        } else {
            x.className = x.className.replace("w3-show", "");
            x.previousElementSibling.className =
                x.previousElementSibling.className.replace(" w3-theme-d1", "");
        }
    }

    // Used to toggle the menu on smaller screens when clicking on the menu button
    function openNav() {
        var x = document.getElementById("navDemo");
        if (x.className.indexOf("w3-show") == -1) {
            x.className += " w3-show";
        } else {
            x.className = x.className.replace(" w3-show", "");
        }
    }
</script>

</body>
{% endblock %}
</html>